[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
evm_version='shanghai'
[fuzz]
seed = "0x2"
runs = 10000
[invariant]
runs = 100000
depth = 32
fail_on_revert = false


remappings = ['foundry-huff/=lib/foundry-huff/src']
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Add compiler settings for specific contracts
